config/routes.rb
Rails.application.routes.draw do
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'home', to: 'home#show'
  get 'help', to: 'help#show'

  get '/users/me', to: 'users#me', as: 'me'

  get 'login', to: redirect('/auth/google'), as: 'login'
  get '/auth/google/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#show'

  get 'filter_sections_by_course', to: "courses#filter_sections_by_course"

  resources :users
  resources :courses
  resources :sections
  resources :timeslots

  root to: "home#show"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate

  def index
  end

  def show
    search_fields = params.permit()

    @users = User.all
    # @users = @users.where(course_id: current_user.course_id)
    @users = @users.where(section_id: current_user.section_id)
    @users = @users.where(searching: true)
    @users = @users.where.not(id: current_user.id)

    if @users.empty?
      redirect_back fallback_location: search_path, flash: {error: "No matching users found."}
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<h1>Search for a partner</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= bootstrap_form_tag(method: :get, url: search_results_path) do |f| %>
      <h2>Show students who are:</h2>

      <% defaults = 
        [
          :in_my_section, 
          :available,
        ] %>
      <% other_boxes =
        [
        ] %>

      <% for default in defaults %>
        <div class="form-group">
          <%= f.check_box default, checked: "checked", disabled: true %>
        </div>
      <% end %>
      <% for box in other_boxes %>
        <div class="form-group">
          <%= box %>
        </div>
      <% end %>
      <div class="form-group" align="center">
        <%= f.submit "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/search/show.html.erb
<h1>Search results</h1>
<h2><%= link_to "Go back", search_path %></h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Result</th>
      <th scope="col">Lab Section</th>
      <th scope="col">Availability Match</th>
    </tr>
  </thead>
  <% i = 0 %>
  <% @users.each do |user| %>
    <% i += 1 %>
    <tr>
      <td class="user-td"><%= i %>
      <td class="user-td"><%= user.section.link_or_unspec %></td>
      <td class="user.td"><%= user.availability_match(current_user) %></td>
    </tr>
  <% end %>
</table>