config/routes.rb
Rails.application.routes.draw do
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'home', to: 'home#show'
  get 'help', to: 'help#show'

  get '/users/me', to: 'users#me', as: 'me'

  get 'login', to: redirect('/auth/google'), as: 'login'
  get '/auth/google/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#show'

  get 'filter_sections_by_course', to: "courses#filter_sections_by_course"

  resources :users
  resources :courses
  resources :sections
  resources :timeslots

  root to: "home#show"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :course
  belongs_to :section
  has_many :timeslots

  validates :email, format: { with: /\A.*@(husky\.neu|northeastern)\.edu\z/, message: "must be an @husky.neu.edu or @northeastern.edu address"}
  validates :course_id, :section_id, presence: true
  validate :section_matches_course

  def section_matches_course
    if section.course != course
      errors.add(:section, "must be in selected course.")
    end
  end

  def self.find_or_create_from_auth_hash(auth)
    where(uid: auth.uid).first_or_initialize.tap do |user|
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.course ||= Course.where(name: "Unspecified").first
      user.section ||= user.course.sections.first
      user.searching = true if user.searching.nil?
      user.save!
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def profile_photo(size)
    ActionController::Base.helpers.image_tag picture, alt: "#{full_name}'s profile photo", id: "propic", size: size
  end

  def picture_set?
    picture != "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/c/photo.jpg"
  end

  def availability_match(other_user)
    sum = 0
    timeslots.each do |mine|
      other_user.timeslots.each do |theirs|
        sum += mine.overlap_hours(theirs)
      end
    end
    return "#{sum} hours"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :require_admin, only: "index"

  def index
    @users = User.all
  end

  def show
    begin
      @user = User.find params[:id]
    rescue
      @user = nil
    end
    if @user.nil? or @user.id != current_user.id and !current_user.admin?
      redirect_back(fallback_location: current_user, flash: {error: "You do not have permission to access that page."})
      return
    end
  end

  def edit
    if current_user.id.to_s != params[:id] and !current_user.admin?
      byebug
      redirect_back(fallback_location: current_user, flash: {error: "You do not have permission to access that page."})
      return
    end
    @user = User.where(id: params[:id]).first
  end

  def update
    new_values = params.require(:user).permit(:course_id, :section_id, :searching)
    @user = User.where(id: params[:id]).first
    if @user.id != current_user.id and !current_user.admin?
      redirect_back fallback_location: root_path, flash: {error: "You do not have permission to access that page."}
      return
    end
    if @user.update_attributes(new_values)
      redirect_to @user, flash: {notice: "Successfully updated profile."}
    else
      redirect_back fallback_location: @user, flash: {error: @user.errors.full_messages.to_sentence}
    end
  end

  def me
    redirect_to current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit profile</h1>
<h2><%= @user.full_name %></h2>
<div class="row">
  <div class="col-sm-8 offset-sm-2" align="center">
    <% if @user.picture_set? %>
      <%= @user.profile_photo 150 %>
    <% else %>
      <p>Please consider <%= link_to "setting a profile picture", "https://myaccount.google.com/" %>, so that those you match with will be able to identify you.</p>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= bootstrap_form_for(@user) do |f| %>
      <%= f.collection_select :course_id, Course.all, :id, :name %>
      <%= f.collection_select :section_id, @user.course.sections, :id, :desc %>
      <div class="form-group">
        <%= f.check_box :searching %>
      </div>
      <%= link_to "Edit availability", timeslots_path %>
      <div class="row" style="padding-top: 20px;">
        <div class="col-md-12" align="center">
          <%= f.submit "Save changes", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users (admin)</h1>
<h2><%= pluralize User.all.length, "user" %> total.</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">User</th>
      <th scope="col">Course</th>
      <th scope="col">Lab Section</th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td class="user-td"><%= user.profile_photo(60) %></td>
      <td class="user-td"><%= link_to user.full_name, user %></td>
      <td class="user-td"><%= user.course.link_or_unspec %></td>
      <td class="user-td"><%= user.section.link_or_unspec %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<div class="row">
  <div class="col-md-2 offset-md-1" align="center">
    <%= @user.profile_photo 150 %>
    <br><br>
  </div>
  <div class="col-md-6 offset-md-1">
    <table class="table">
      <tr>
        <td><strong>Course</strong></td>
        <td><%= @user.course.link_or_unspec %></td>
      </tr>
      <tr>
        <td><strong>Lab Section</strong></td>
        <td><%= @user.section.link_or_unspec %></td>
      </tr>
      <tr>
        <td><strong>Searching</strong></td>
        <td><%= @user.searching ? "Yes" : "No" %></td>
      </tr>
      <tr>
        <td><strong>Availability</strong></td>
        <td>
          <% if @user.timeslots.empty? %>
            None
          <% else %>
            <ul>
              <% @user.timeslots.each do |timeslot| %>
                <li><%= timeslot.desc %></li>
              <% end %>
            </ul>
          <% end %>
        </td>
    </table>
  </div>
</div>
<% if @user.id == current_user.id or current_user.admin? %>
  <div class="row" style="padding-top: 20px;">
    <div class="col-md-12" align="center">
      <%= button_to "Edit profile", edit_user_path(@user), method: :get, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>