config/routes.rb
Rails.application.routes.draw do
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'home', to: 'home#show'
  get 'help', to: 'help#show'

  get '/users/me', to: 'users#me', as: 'me'

  get 'login', to: redirect('/auth/google'), as: 'login'
  get '/auth/google/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#show'

  get 'filter_sections_by_course', to: "courses#filter_sections_by_course"

  resources :users
  resources :courses
  resources :sections
  resources :timeslots

  root to: "home#show"
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :user

  validate :hours_valid
  validate :minutes_valid
  validate :in_correct_week
  validate :does_not_cross_day
  validate :start_before_end
  validate :timeslots_dont_overlap

  def self.display_hours
    pad_range(0..23)
  end

  def self.display_minutes
    pad_range(0..59)
  end

  def self.pad_range(r)
    r.map do |item|
      "%02d" % item
    end
  end

  def hours_valid
    unless start_hour >= 0 and start_hour <= 23
      errors.add(:start_hour, "must be between 0 and 23")
    end
    unless end_hour >= 0 and end_hour <= 23
      errors.add(:end_hour, "must be between 0 and 23")
    end
  end

  def minutes_valid
    unless start_minute >= 0 and start_minute <= 59
      errors.add(:start_minute, "must be between 0 and 59")
    end
    unless end_minute >= 0 and end_minute <= 59
      errors.add(:end_minute, "must be between 0 and 59")
    end
  end

  def start_time
    return DateTime.new(2018, 04, day, start_hour, start_minute)
  end

  def end_time
    return DateTime.new(2018, 04, day, end_hour, end_minute)
  end

  def in_correct_week
    unless start_time >= Timeslot.min_start_date
      errors.add(:start_time, "must be between #{Timeslot.min_start_date} and #{Timeslot.max_end_date}")
    end
    unless end_time <= Timeslot.max_end_date
      errors.add(:end_time, "must be between #{Timeslot.min_start_date} and #{Timeslot.max_end_date}")
    end
  end

  def does_not_cross_day
    if start_time.day != end_time.day
      errors.add(:start_time, "must be on same day as end time")
    end
  end

  def start_before_end
    unless start_time < end_time
      errors.add(:start_time, "must be before end time")
    end
  end

  def timeslots_dont_overlap
    user.timeslots.each do |other|
      if overlaps? other
        errors.add(:timeslots, "must not overlap")
      end
    end
  end

  def self.min_start_date
    DateTime.new(2018, 4, 1, 0, 0)
  end
  
  def self.max_end_date
    DateTime.new(2018, 4, 7, 23, 59)
  end

  def overlaps?(other)
    return false if id == other.id 
    start_time <= other.end_time and other.start_time <= end_time
  end

  def overlap_hours(other)
    return 0 if !overlaps?(other) 
    later_start = start_time > other.start_time ? start_time : other.start_time
    earlier_end = end_time < other.end_time ? end_time : other.end_time
    return ((earlier_end - later_start) * 24).to_f # difference in days by default
  end

  def day_of_week
    start_time.strftime("%A")
  end

  def time
    start_time.strftime("%l:%M%P") + " to " + end_time.strftime("%l:%M%P")
  end

  def desc
    "#{day_of_week}s, #{time}"
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :authenticate

  def index
    if current_user.admin?
      @timeslots = Timeslot.all
    else
      @timeslots = current_user.timeslots
    end
  end

  def new
  end

  def create
    timeslot_params = params.require(:timeslot).permit(:day, :start_hour, :start_minute, :end_hour, :end_minute)
    timeslot_params[:user] = current_user
    @timeslot = Timeslot.create(timeslot_params)
    if @timeslot.save
      redirect_to timeslots_path
    else
      redirect_back fallback_location: new_timeslot_path, flash: {error: @timeslot.errors.full_messages.to_sentence}
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])
    if @timeslot.user.id != current_user.id and !current_user.admin?
      redirect_back(fallback_location: root_path, flash: {error: "You do not have permission to access that page."})
      return
    end
    @timeslot.destroy
    redirect_to timeslots_path
  end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/index.html.erb
<h1>Timeslots</h1>
<h2><%= link_to "Go back", edit_user_path(current_user) %></h2>
<div align="center" style="margin:10px">
  <%= button_to "New", new_timeslot_path, method: :get, class: "btn btn-success" %>
</div>
<% if @timeslots.empty? %>
  <h2>No timeslots yet.</h2>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>User name</th>
        <th>Times</th>
        <th></th>
      </tr>
    </thead>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td class="user-td"><%= timeslot.user.full_name %></td>
        <td class="user-td"><%= timeslot.desc %></td>
        <td class="user-td"><%= button_to "Delete", timeslot_path(timeslot), method: :delete, class: "btn btn-danger" %>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/timeslots/new.html.erb
<h1>New Timeslot</h1>
<h2><%= current_user.full_name %></h2>
<div class="row">
  <div class="col-sm-4 offset-sm-4">
    <% @n=0 %>
    <%= bootstrap_form_for(:timeslot, url: "/timeslots") do |f| %>
      <%= f.collection_select :day, Date::DAYNAMES, Proc.new {@n+=1}, :to_s %>
      <table align="center" class="time-table">
        <tr><td>Start time</td></tr>
        <tr>
          <td><%= f.select :start_hour, Timeslot.display_hours, label: "&nbsp;".html_safe %></td>
          <td class="time-colon"><strong>:</strong></td>
          <td><%= f.select :start_minute, Timeslot.display_minutes, label: "&nbsp;".html_safe %></td>
        </tr>
      </table>
      <table align="center" class="time-table">
        <tr><td>End time</td></tr>
        <tr>
          <td><%= f.select :end_hour, Timeslot.display_hours, label: "&nbsp;".html_safe %></td>
          <td class="time-colon"><strong>:</strong></td>
          <td><%= f.select :end_minute, Timeslot.display_minutes, label: "&nbsp;".html_safe %></td>
        </tr>
      </table>
      <div class="center">
        <%= f.submit "Create timeslot", class: "btn btn-success" %>
      </div>
    <% end %>
    <div class="cancel-button center">
      <%= button_to "Cancel", timeslots_path, method: :get, class: "btn btn-warning" %>
    </div>
  </div>
</div>