config/routes.rb
Rails.application.routes.draw do
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  get 'home', to: 'home#show'
  get 'help', to: 'help#show'

  get '/users/me', to: 'users#me', as: 'me'

  get 'login', to: redirect('/auth/google'), as: 'login'
  get '/auth/google/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'search', to: 'search#index'
  get 'search/results', to: 'search#show'

  get 'filter_sections_by_course', to: "courses#filter_sections_by_course"

  resources :users
  resources :courses
  resources :sections
  resources :timeslots

  root to: "home#show"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to image_tag("orca.svg", alt: "Orca"), root_path, id: "logo", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <% if !user_signed_in? %>
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Search for a partner", search_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "My profile", me_path, class: "nav-link" %></li>
      <% end %>
      <% if user_signed_in? and current_user.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
            Admin
          </a>
          <div class="dropdown-menu">
            <%= link_to "All users", users_path, class: "dropdown-item" %>
            <%= link_to "All courses", courses_path, class: "dropdown-item" %>
            <%= link_to "All sections", sections_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "Help", help_path, class: "nav-link" %></li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Log out", logout_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orca</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'application/favicon' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/error_messages' %>
      <%= yield %>
    </div>
  </body>
</html>